### PR TITLE
Add dummy file

### PR DESCRIPTION
**Pull request by jfmengels**

### CODE REVIEW

**Comment by sparksp** [comment]
This is an interesting change - is this because the action has 'master' hard coded in? Because publish should be safe to run otherwise.

**Comment by jfmengels** [comment]
> This is an interesting change - is this because the action has 'master' hard coded in? Because publish should be safe to run otherwise.

Yes, if people prefer `main` (as I intend to do for my own repos), then that should work for them too.
Also, I am a bit worried that someone bumping a version in a PR would lead to the version being published, I'm not sure how that works... (EDIT: Looks like `elm-publish-action` already does that)

Also, if possible, I just want to skip the extra seconds waiting on the publish action to complete. Looks like my experiment doesn't work out well, so I'm not sure what I need to do here :thinking:

**Comment by sparksp** [comment]
I just went to check and the action already handles master vs main (well done Dillon) and only actually publishes commits to that branch.

**Comment by jfmengels** [comment]
Yes, I arrived to the same conclusion. It would be nice if we could prevent that step from starting to avoid a scare from the maintainer (I plan to copy the same script for `elm-review new-package`) and to save a few seconds. I'm not sure this is possible at the moment though.

**Pull request closed without merging**
